[package]
name = "rust-game-chess"
version = "0.1.0"
authors = ["richelbilderbeek <richel@richelbilderbeek.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "rust-game-chess"
path = "main.rs"
